
branches:
  only:
  - master
language: r
sudo: false
cache: 
  packages: yes
pandoc_version: 2.2.1

addons:
  apt:
    packages:
      - python2.7
      - python-numpy

script:
  - git config --global user.email "romain.lesur@gmail.com"
  - git config --global user.name "Romain Lesur"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git output
  - cp ./*.Rmd ./output
  - cp -r ./assets ./output
  - cp -r ./node ./output
  - cp -r ./sql ./output
  - cd output
  - Rscript -e "rmarkdown::render('simple.Rmd')"
  - Rscript -e "rmarkdown::render('index.Rmd')"
  - git add --all -f ./*
  - git commit -m"Update site"
  - git push origin gh-pages
