branches:
  only:
  - master
language: r
sudo: false
cache: 
  packages: yes
pandoc_version: 2.2.1

script:
  - Rscript -e "rmarkdown::render('index.Rmd')"
  - git config --global user.email "romain.lesur@gmail.com"
  - git config --global user.name "Romain Lesur"
  - git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git output
  - cp -R ./* ./output
  - cd output
  - git add --all -f ./*
  - git commit -m"Update site"
  - git push origin gh-pages
